[package]
name = "wasi-cap-std-sync"
version = "0.40.0"
authors = ["The Wasmtime Project Developers"]
description = "WASI implementation in Rust"
license = "Apache-2.0 WITH LLVM-exception"
categories = ["wasm"]
keywords = ["webassembly", "wasm"]
repository = "https://github.com/bytecodealliance/wasmtime"
readme = "README.md"
edition = "2021"
include = ["src/**/*", "README.md", "LICENSE" ]

[dependencies]
wasi-common = { path = "../", version = "=0.40.0" }
async-trait = "0.1"
anyhow = "1.0"
cap-std = "0.25.0"
cap-fs-ext = "0.25.0"
cap-time-ext = "0.25.0"
cap-rand = "0.25.0"
fs-set-times = "0.17.0"
system-interface = { version = "0.21.0", features = ["cap_std_impls"] }
tracing = "0.1.19"
io-lifetimes = { version = "0.7.0", default-features = false }
is-terminal = "0.3.0"

[target.'cfg(unix)'.dependencies]
rustix = { version = "0.35.6", features = ["fs"] }

[target.'cfg(windows)'.dependencies]
once_cell = "1.12.0"
io-extras = "0.15.0"

[target.'cfg(windows)'.dependencies.windows-sys]
version = "0.36.0"
features = [
    "Win32_Foundation",
]

[dev-dependencies]
tempfile = "3.1.0"
