[package]
authors = ["The Cranelift Project Developers"]
name = "cranelift-reader"
version = "0.112.1"
description = "Cranelift textual IR reader"
license = "Apache-2.0 WITH LLVM-exception"
documentation = "https://docs.rs/cranelift-reader"
repository = "https://github.com/bytecodealliance/wasmtime"
readme = "README.md"
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true, features = ['std'] }
cranelift-codegen = { workspace = true }
smallvec = { workspace = true }
target-lexicon = { workspace = true, features = ['std'] }
