[package]
name = "cranelift-tools"
authors = ["The Cranelift Project Developers"]
version = "0.22.0"
description = "Binaries for testing the Cranelift libraries"
license = "Apache-2.0 WITH LLVM-exception"
documentation = "https://cranelift.readthedocs.io/"
repository = "https://github.com/CraneStation/cranelift"
publish = false

[[bin]]
name = "clif-util"
path = "src/clif-util.rs"

[dependencies]
cfg-if = "0.1"
cranelift-codegen = { path = "lib/codegen", version = "0.22.0" }
cranelift-entity = { path = "lib/entity", version = "0.22.0" }
cranelift-reader = { path = "lib/reader", version = "0.22.0" }
cranelift-frontend = { path = "lib/frontend", version = "0.22.0" }
cranelift-serde = { path = "lib/serde", version = "0.22.0", optional = true }
cranelift-wasm = { path = "lib/wasm", version = "0.22.0", optional = true }
cranelift-native = { path = "lib/native", version = "0.22.0" }
cranelift-filetests = { path = "lib/filetests", version = "0.22.0" }
cranelift-module = { path = "lib/module", version = "0.22.0" }
cranelift-faerie = { path = "lib/faerie", version = "0.22.0" }
cranelift-simplejit = { path = "lib/simplejit", version = "0.22.0" }
cranelift-preopt = { path = "lib/preopt", version = "0.22.0" }
cranelift = { path = "lib/umbrella", version = "0.22.0" }
filecheck = "0.4.0"
clap = "2.32.0"
serde = "1.0.8"
term = "0.5.1"
capstone = { version = "0.5.0", optional = true }
wabt = { version = "0.7.0", optional = true }
target-lexicon = "0.2.0"
pretty_env_logger = "0.2.4"
file-per-thread-logger = "0.1.1"

[features]
default = ["disas", "wasm"]
disas = ["capstone"]
wasm = ["wabt", "cranelift-wasm"]

[workspace]

# We want debug symbols on release binaries by default since it allows profiling
# tools to give more accurate information. We can always strip them out later if
# necessary.
[profile.release]
debug = true
[profile.bench]
debug = true
