[package]
name = "cranelift-tools"
authors = ["The Cranelift Project Developers"]
version = "0.17.0-alpha"
description = "Binaries for testing the Cranelift libraries"
license = "Apache-2.0 WITH LLVM-exception"
documentation = "https://cranelift.readthedocs.io/"
repository = "https://github.com/CraneStation/cranelift"
publish = false

[[bin]]
name = "clif-util"
path = "src/clif-util.rs"

[dependencies]
cfg-if = "0.1"
cranelift-codegen = { path = "lib/codegen", version = "0.17.0-alpha" }
cranelift-reader = { path = "lib/reader", version = "0.17.0-alpha" }
cranelift-frontend = { path = "lib/frontend", version = "0.17.0-alpha" }
cranelift-wasm = { path = "lib/wasm", version = "0.17.0-alpha", optional = true }
cranelift-native = { path = "lib/native", version = "0.17.0-alpha" }
cranelift-filetests = { path = "lib/filetests", version = "0.17.0-alpha" }
cranelift-module = { path = "lib/module", version = "0.17.0-alpha" }
cranelift-faerie = { path = "lib/faerie", version = "0.17.0-alpha" }
cranelift-simplejit = { path = "lib/simplejit", version = "0.17.0-alpha" }
cranelift = { path = "lib/umbrella", version = "0.17.0-alpha" }
filecheck = "0.3.0"
docopt = "1"
serde = "1.0.8"
serde_derive = "1.0.8"
term = "0.5.1"
capstone = { version = "0.4", optional = true }
wabt = { version = "0.4", optional = true }
target-lexicon = "0.0.3"

[features]
default = ["disas", "wasm"]
disas = ["capstone"]
wasm = ["wabt", "cranelift-wasm"]

[workspace]

# We want debug symbols on release binaries by default since it allows profiling
# tools to give more accurate information. We can always strip them out later if
# necessary.
[profile.release]
debug = true
[profile.bench]
debug = true
