[package]
name = "cranelift-tools"
authors = ["The Cranelift Project Developers"]
version = "0.56.0"
description = "Binaries for testing the Cranelift libraries"
license = "Apache-2.0 WITH LLVM-exception"
documentation = "https://cranelift.readthedocs.io/"
repository = "https://github.com/bytecodealliance/cranelift"
publish = false
edition = "2018"

# Present here only to make sure that cargo test --all runs tests for all
# the crates.
[workspace]

[[bin]]
name = "clif-util"
path = "src/clif-util.rs"

[dependencies]
cfg-if = "0.1"
cranelift-codegen = { path = "cranelift-codegen", version = "0.56.0" }
cranelift-entity = { path = "cranelift-entity", version = "0.56.0" }
cranelift-reader = { path = "cranelift-reader", version = "0.56.0" }
cranelift-frontend = { path = "cranelift-frontend", version = "0.56.0" }
cranelift-serde = { path = "cranelift-serde", version = "0.56.0", optional = true }
cranelift-wasm = { path = "cranelift-wasm", version = "0.56.0", optional = true }
cranelift-native = { path = "cranelift-native", version = "0.56.0" }
cranelift-filetests = { path = "cranelift-filetests", version = "0.56.0" }
cranelift-module = { path = "cranelift-module", version = "0.56.0" }
cranelift-faerie = { path = "cranelift-faerie", version = "0.56.0" }
cranelift-object = { path = "cranelift-object", version = "0.56.0" }
cranelift-simplejit = { path = "cranelift-simplejit", version = "0.56.0" }
cranelift-preopt = { path = "cranelift-preopt", version = "0.56.0" }
cranelift = { path = "cranelift-umbrella", version = "0.56.0" }
filecheck = "0.4.0"
clap = "2.32.0"
serde = "1.0.8"
term = "0.6.1"
capstone = { version = "0.6.0", optional = true }
wat = { version = "1.0.7", optional = true }
target-lexicon = "0.10"
pretty_env_logger = "0.3.0"
file-per-thread-logger = "0.1.2"
indicatif = "0.13.0"
walkdir = "2.2"

[features]
default = ["disas", "wasm", "cranelift-codegen/all-arch"]
disas = ["capstone"]
wasm = ["wat", "cranelift-wasm"]

# We want debug symbols on release binaries by default since it allows profiling
# tools to give more accurate information. We can always strip them out later if
# necessary.
[profile.release]
debug = true
# debug-assertions = true # uncomment to make bugpoint blazingly fast!
[profile.bench]
debug = true
