[package]
name = "cranelift-tools"
authors = ["The Cranelift Project Developers"]
version = "0.59.0"
description = "Binaries for testing the Cranelift libraries"
license = "Apache-2.0 WITH LLVM-exception"
documentation = "https://github.com/bytecodealliance/wasmtime/blob/master/cranelift/docs/index.md"
repository = "https://github.com/bytecodealliance/cranelift"
publish = false
edition = "2018"

[[bin]]
name = "clif-util"
path = "src/clif-util.rs"

[dependencies]
cfg-if = "0.1"
cranelift-codegen = { path = "codegen", version = "0.59.0" }
cranelift-entity = { path = "entity", version = "0.59.0" }
cranelift-reader = { path = "reader", version = "0.59.0" }
cranelift-frontend = { path = "frontend", version = "0.59.0" }
cranelift-serde = { path = "serde", version = "0.59.0", optional = true }
cranelift-wasm = { path = "wasm", version = "0.59.0", optional = true }
cranelift-native = { path = "native", version = "0.59.0" }
cranelift-filetests = { path = "filetests", version = "0.59.0" }
cranelift-module = { path = "module", version = "0.59.0" }
cranelift-faerie = { path = "faerie", version = "0.59.0" }
cranelift-object = { path = "object", version = "0.59.0" }
cranelift-simplejit = { path = "simplejit", version = "0.59.0" }
cranelift-preopt = { path = "preopt", version = "0.59.0" }
cranelift = { path = "umbrella", version = "0.59.0" }
filecheck = "0.4.0"
clap = "2.32.0"
serde = "1.0.8"
term = "0.6.1"
capstone = { version = "0.6.0", optional = true }
wat = { version = "1.0.7", optional = true }
target-lexicon = "0.10"
pretty_env_logger = "0.3.0"
file-per-thread-logger = "0.1.2"
indicatif = "0.13.0"
walkdir = "2.2"

[features]
default = ["disas", "wasm", "cranelift-codegen/all-arch"]
disas = ["capstone"]
wasm = ["wat", "cranelift-wasm"]
