[package]
name = "wasmtime-rust"
version = "0.12.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
description = "Rust extension for Wasmtime"
license = "Apache-2.0 WITH LLVM-exception"
categories = ["wasm"]
keywords = ["webassembly", "wasm"]
repository = "https://github.com/bytecodealliance/wasmtime"
readme = "README.md"
edition = "2018"

[lib]
test = false
doctest = false

[dependencies]
wasmtime-interface-types = { path = "../../interface-types", version = "0.12.0" }
wasmtime-rust-macro = { path = "./macro", version = "0.12.0" }
wasmtime-wasi = { path = "../../wasi", version = "0.12.0" }
wasmtime = { path = "../../api", version = "0.12.0" }
anyhow = "1.0.19"

[badges]
maintenance = { status = "actively-developed" }
