[package]
name = "wasmtime-rust"
version = "0.2.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
description = "Rust extension for Wasmtime"
license = "Apache-2.0 WITH LLVM-exception"
categories = ["wasm", "rust"]
keywords = ["webassembly", "wasm"]
repository = "https://github.com/bytecodealliance/wasmtime"
readme = "README.md"
edition = "2018"

[lib]
test = false
doctest = false

[dependencies]
cranelift-codegen = "0.50.0"
cranelift-native = "0.50.0"
wasmtime-interface-types = { path = "../../interface-types" }
wasmtime-jit = { path = "../../jit" }
wasmtime-rust-macro = { path = "./macro" }
wasmtime-wasi = { path = "../../wasi" }
anyhow = "1.0.19"

[badges]
maintenance = { status = "actively-developed" }
