[package]
name = "cranelift-serde"
version = "0.104.3"
authors = ["The Cranelift Project Developers"]
description = "Serializer/Deserializer for Cranelift IR"
repository = "https://github.com/bytecodealliance/wasmtime"
license = "Apache-2.0 WITH LLVM-exception"
readme = "README.md"
keywords = ["webassembly", "serde"]
edition.workspace = true

[lints]
workspace = true

[[bin]]
name = "clif-json"
path = "src/clif-json.rs"

[dependencies]
clap = { workspace = true }
serde_json = "1.0.26"
cranelift-codegen = { workspace = true, features = ["enable-serde"] }
cranelift-reader = { workspace = true }
