[package]
name = "wasi-http-tests"
version = "0.0.0"
readme = "README.md"
edition = "2021"
publish = false
test = false

[dependencies]
anyhow = { workspace = true }
wit-bindgen = { workspace = true }
