[package]
name = "wasi-http-tests"
version = "0.0.0"
readme = "README.md"
edition = "2021"
publish = false

[dependencies]
anyhow = { workspace = true }
wit-bindgen = { workspace = true, default-features = false, features = ["macros"] }
