[package]
authors = ["The Cranelift Project Developers"]
description = "ISLE: Instruction Selection and Lowering Expressions. A domain-specific language for instruction selection in Cranelift."
edition = "2021"
license = "Apache-2.0 WITH LLVM-exception"
name = "cranelift-isle"
readme = "../README.md"
repository = "https://github.com/bytecodealliance/wasmtime/tree/main/cranelift/isle"
version = "0.85.0"

[dependencies]
log = { version = "0.4", optional = true }
miette = { version = "4.7.0", optional = true }

[dev-dependencies]
tempfile = "3"

[features]
default = []

logging = ["log"]
miette-errors = ["miette"]
