[package]
name = "wasmtime-c-api-macros"
version.workspace = true
authors = ["The Wasmtime Project Developers"]
license = "Apache-2.0 WITH LLVM-exception"
edition.workspace = true
rust-version.workspace = true
description = "Support macros for `wasmtime-c-api`"
repository = "https://github.com/bytecodealliance/wasmtime"

[lints]
workspace = true

[lib]
proc-macro = true
test = false
doctest = false

[dependencies]
quote = "1.0"
proc-macro2 = "1.0"
