[package]
name = "pulley-interpreter-fuzz"
version = "0.0.0"
publish = false
edition.workspace = true

[package.metadata]
cargo-fuzz = true

[dependencies]
pulley-interpreter = { path = "..", features = ["encode", "decode", "disas", "interp", "arbitrary"] }
env_logger = { workspace = true }
libfuzzer-sys = { workspace = true }
log = { workspace = true }

[[bin]]
name = "roundtrip"
path = "fuzz_targets/roundtrip.rs"
test = false
doc = false
bench = false

[[bin]]
name = "interp"
path = "fuzz_targets/interp.rs"
test = false
doc = false
bench = false
