[package]
name = "wiggle-test"
version = "0.14.0"
authors = ["Pat Hickey <phickey@fastly.com>", "Jakub Konka <kubkon@jakubkonka.com>", "Alex Crichton <alex@alexcrichton.com>"]
license = "Apache-2.0 WITH LLVM-exception"
edition = "2018"
description = "Reusable testing components for wiggle code generator. Only intended to be used by tests in `wiggle` crate."
categories = ["wasm"]
keywords = ["webassembly", "wasm"]
repository = "https://github.com/bytecodealliance/wasmtime"
include = ["src/**/*", "LICENSE"]

[dependencies]
proptest = "0.9"
wiggle = { path = "..", version = "0.14.0" }

[badges]
maintenance = { status = "actively-developed" }
