[package]
name = "wasmtime-fiber"
version.workspace = true
authors.workspace = true
description = "Fiber support for Wasmtime"
license = "Apache-2.0 WITH LLVM-exception"
repository = "https://github.com/bytecodealliance/wasmtime"
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
cfg-if = { workspace = true }
wasmtime-versioned-export-macros = { workspace = true }

[target.'cfg(unix)'.dependencies]
rustix = { workspace = true, features = ["mm", "param"] }
wasmtime-asm-macros = { workspace = true }

[target.'cfg(windows)'.dependencies.windows-sys]
workspace = true
features = [
  "Win32_System_Threading",
  "Win32_Foundation",
]

[build-dependencies]
cc = "1.0"
wasmtime-versioned-export-macros = { workspace = true }

[dev-dependencies]
backtrace = "0.3.68"
