[package]
name = "wasmtime-fiber"
version = "0.40.0"
authors = ["The Wasmtime Project Developers"]
description = "Fiber support for Wasmtime"
license = "Apache-2.0 WITH LLVM-exception"
repository = "https://github.com/bytecodealliance/wasmtime"
edition = "2021"

# We link to some native code with symbols that don't change often, so let Cargo
# know that we can't show up multiple times in a crate graph. If this is an
# issue in the future we should tweak the build script to set `#define`
# directives or similar to embed a version number of this crate in symbols.
links = "wasmtime-fiber-shims"

[dependencies]
cfg-if = "1.0"

[target.'cfg(unix)'.dependencies]
rustix = { version = "0.35.6", features = ["mm", "param"] }
wasmtime-asm-macros = { version = "=0.40.0", path = "../asm-macros" }

[target.'cfg(windows)'.dependencies.windows-sys]
version = "0.36.1"
features = [
  "Win32_System_Threading",
  "Win32_Foundation",
]

[build-dependencies]
cc = "1.0"

[dev-dependencies]
backtrace = "0.3.61"
