[package]
name = "cranelift-module"
version = "0.78.0"
authors = ["The Cranelift Project Developers"]
description = "Support for linking functions and data with Cranelift"
repository = "https://github.com/bytecodealliance/wasmtime"
documentation = "https://docs.rs/cranelift-module"
categories = ["no-std"]
license = "Apache-2.0 WITH LLVM-exception"
readme = "README.md"
edition = "2018"

[dependencies]
cranelift-codegen = { path = "../codegen", version = "0.78.0", default-features = false }
cranelift-entity = { path = "../entity", version = "0.78.0" }
hashbrown = { version = "0.9.1", optional = true }
log = { version = "0.4.6", default-features = false }
anyhow = "1.0"

[features]
default = ["std"]
std = ["cranelift-codegen/std"]
core = ["hashbrown", "cranelift-codegen/core"]

[badges]
maintenance = { status = "experimental" }
