[package]
name = "cranelift-module"
version = "0.46.0"
authors = ["The Cranelift Project Developers"]
description = "Support for linking functions and data with Cranelift"
repository = "https://github.com/CraneStation/cranelift"
documentation = "https://cranelift.readthedocs.io/"
categories = ["no-std"]
license = "Apache-2.0 WITH LLVM-exception"
readme = "README.md"
edition = "2018"

[dependencies]
cranelift-codegen = { path = "../cranelift-codegen", version = "0.46.0", default-features = false }
cranelift-entity = { path = "../cranelift-entity", version = "0.46.0" }
hashbrown = { version = "0.6", optional = true }
failure = { version = "0.1.1", default-features = false }
log = { version = "0.4.6", default-features = false }

[features]
default = ["std"]
std = ["cranelift-codegen/std"]
core = ["hashbrown", "cranelift-codegen/core"]

[badges]
maintenance = { status = "experimental" }
travis-ci = { repository = "CraneStation/cranelift" }
