[package]
name = "wasmtime-runtime"
version.workspace = true
authors.workspace = true
description = "Runtime library support for Wasmtime"
documentation = "https://docs.rs/wasmtime-runtime"
license = "Apache-2.0 WITH LLVM-exception"
categories = ["wasm"]
keywords = ["webassembly", "wasm"]
repository = "https://github.com/bytecodealliance/wasmtime"
edition.workspace = true

[lints]
workspace = true

[dependencies]
wasmtime-wmemcheck = { workspace = true, optional = true }
wasmtime-asm-macros = { workspace = true }
wasmtime-environ = { workspace = true }
wasmtime-fiber = { workspace = true, optional = true }
wasmtime-jit-debug = { workspace = true, features = ["gdb_jit_int"], optional = true }
wasmtime-versioned-export-macros = { workspace = true }
wasmtime-slab = { workspace = true }
libc = { workspace = true }
log = { workspace = true }
memoffset = "0.9.0"
indexmap = { workspace = true }
cfg-if = { workspace = true }
anyhow = { workspace = true }
paste = "1.0.3"
encoding_rs = { version = "0.8.31", optional = true }
sptr = "0.3.2"
wasm-encoder = { workspace = true, optional = true }

[target.'cfg(target_os = "linux")'.dependencies]
memfd = "0.6.2"

[target.'cfg(target_os = "macos")'.dependencies]
mach2 = "0.4.1"

[target.'cfg(unix)'.dependencies]
rustix = { workspace = true, features = ["mm"] }

[target.'cfg(target_os = "windows")'.dependencies.windows-sys]
workspace = true
features = [
  "Win32_Foundation",
  "Win32_System_Kernel",
  "Win32_System_Memory",
  "Win32_System_Diagnostics_Debug",
  "Win32_System_SystemInformation",
  "Win32_Storage_FileSystem",
  "Win32_Security",
]

[target.'cfg(target_arch = "s390x")'.dependencies]
psm = "0.1.11"

[dev-dependencies]
once_cell = { workspace = true }
proptest = "1.0.0"
rand = { version = "0.8.3", features = ['small_rng'] }

[build-dependencies]
cc = "1.0"
wasmtime-versioned-export-macros = { workspace = true }

[features]
async = ["dep:wasmtime-fiber"]
pooling-allocator = []
component-model = ["wasmtime-environ/component-model", "dep:encoding_rs"]
wmemcheck = ['dep:wasmtime-wmemcheck', 'wasmtime-environ/wmemcheck']
debug-builtins = ['dep:wasmtime-jit-debug']
gc = ["wasmtime-environ/gc"]
coredump = ["dep:wasm-encoder"]
threads = ["wasmtime-environ/threads"]
