[package]
name = "test-programs"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
getrandom = "0.2.8"
rustix = "0.37.9"
cap-std = "1.0.12"
wit-bindgen = { workspace = true, default-features = true }
