[package]
name = "yanix"
version = "0.21.0"
authors = ["The Wasmtime Project Developers"]
description = "Yet Another Nix crate: a Unix API helper library"
documentation = "https://docs.rs/yanix"
license = "Apache-2.0 WITH LLVM-exception"
repository = "https://github.com/bytecodealliance/wasmtime"
edition = "2018"

[dependencies]
tracing = "0.1.15"
libc = { version = "0.2", features = ["extra_traits"] }
bitflags = "1.2"
cfg-if = "1.0"
filetime = "0.2.7"

[badges]
maintenance = { status = "actively-developed" }
