[package]
name = "wasmtime-wasi-nn"
version = "0.38.0"
authors = ["The Wasmtime Project Developers"]
description = "Wasmtime implementation of the wasi-nn API"
documentation = "https://docs.rs/wasmtime-wasi-nn"
license = "Apache-2.0 WITH LLVM-exception"
categories = ["wasm", "computer-vision"]
keywords = ["webassembly", "wasm", "neural-network"]
repository = "https://github.com/bytecodealliance/wasmtime"
readme = "README.md"
edition = "2021"

[dependencies]
# These dependencies are necessary for the witx-generation macros to work:
anyhow = "1.0"
wiggle = { path = "../wiggle", version = "=0.38.0" }

# These dependencies are necessary for the wasi-nn implementation:
openvino = { version = "0.3.3", features = ["runtime-linking"] }
thiserror = "1.0"

[build-dependencies]
walkdir = "2.3"

[badges]
maintenance = { status = "experimental" }
