[package]
name = "wasmtime-wasi-nn"
version.workspace = true
authors.workspace = true
description = "Wasmtime implementation of the wasi-nn API"
documentation = "https://docs.rs/wasmtime-wasi-nn"
license = "Apache-2.0 WITH LLVM-exception"
categories = ["wasm", "computer-vision"]
keywords = ["webassembly", "wasm", "neural-network"]
repository = "https://github.com/bytecodealliance/wasmtime"
readme = "README.md"
edition.workspace = true

[lints]
workspace = true

[dependencies]
# These dependencies are necessary for the WITX-generation macros to work:
anyhow = { workspace = true }
wiggle = { workspace = true }

# This dependency is necessary for the WIT-generation macros to work:
wasmtime = { workspace = true, features = ["component-model"] }

# These dependencies are necessary for the wasi-nn implementation:
tracing = { workspace = true }
openvino = { version = "0.5.0", features = ["runtime-linking"] }
thiserror = { workspace = true }

[build-dependencies]
walkdir = { workspace = true }
