[package]
name = "wasmtime-wasi-nn"
version.workspace = true
authors.workspace = true
description = "Wasmtime implementation of the wasi-nn API"
documentation = "https://docs.rs/wasmtime-wasi-nn"
license = "Apache-2.0 WITH LLVM-exception"
categories = ["wasm", "computer-vision"]
keywords = ["webassembly", "wasm", "neural-network"]
repository = "https://github.com/bytecodealliance/wasmtime"
readme = "README.md"
edition.workspace = true

[dependencies]
# These dependencies are necessary for the witx-generation macros to work:
anyhow = { workspace = true }
wiggle = { workspace = true }

# These dependencies are necessary for the wasi-nn implementation:
openvino = { version = "0.4.1", features = ["runtime-linking"] }
thiserror = "1.0"

[build-dependencies]
walkdir = "2.3"

[badges]
maintenance = { status = "experimental" }
