[package]
name = "wasi-tokio"
version.workspace = true
authors.workspace = true
description = "WASI implementation in Rust"
license = "Apache-2.0 WITH LLVM-exception"
categories = ["wasm"]
keywords = ["webassembly", "wasm"]
repository = "https://github.com/bytecodealliance/wasmtime"
edition.workspace = true
include = ["src/**/*", "LICENSE" ]

[dependencies]
wasi-common = { workspace = true }
wasi-cap-std-sync = { workspace = true }
wiggle = { workspace = true }
tokio = { version = "1.8.0", features = [ "rt", "fs", "time", "io-util", "net", "io-std", "rt-multi-thread"] }
cap-std = { workspace = true }
anyhow = { workspace = true }
io-lifetimes = { workspace = true }

[target.'cfg(unix)'.dependencies]
rustix = { workspace = true, features = ["fs"] }

[target.'cfg(windows)'.dependencies]
io-extras = "0.17.0"

[dev-dependencies]
tempfile = "3.1.0"
tokio = { version = "1.8.0", features = [ "macros" ] }
cap-tempfile = "1.0.0"
