[package]
name = "wasmtime-obj"
version = "0.7.0"
authors = ["The Wasmtime Project Developers"]
description = "Native object file output for WebAsssembly code in Wasmtime"
license = "Apache-2.0 WITH LLVM-exception"
repository = "https://github.com/bytecodealliance/wasmtime"
categories = ["wasm"]
keywords = ["webassembly", "wasm"]
readme = "README.md"
edition = "2018"

[dependencies]
wasmtime-environ = { path = "../environ" }
faerie = "0.13.0"
more-asserts = "0.2.1"

[badges]
maintenance = { status = "experimental" }
