[package]
name = "wasmtime-obj"
version = "0.18.0"
authors = ["The Wasmtime Project Developers"]
description = "Native object file output for WebAsssembly code in Wasmtime"
license = "Apache-2.0 WITH LLVM-exception"
repository = "https://github.com/bytecodealliance/wasmtime"
categories = ["wasm"]
keywords = ["webassembly", "wasm"]
readme = "README.md"
edition = "2018"

[dependencies]
anyhow = "1.0"
wasmtime-environ = { path = "../environ", version = "0.18.0" }
object = { version = "0.20", default-features = false, features = ["write"] }
more-asserts = "0.2.1"
target-lexicon = { version = "0.10.0", default-features = false }
wasmtime-debug = { path = "../debug", version = "0.18.0" }

[badges]
maintenance = { status = "experimental" }
