[package]
name = "wasmtime-c-api"
version.workspace = true
authors.workspace = true
description = "C API to expose the Wasmtime runtime"
license = "Apache-2.0 WITH LLVM-exception"
repository = "https://github.com/bytecodealliance/wasmtime"
readme = "README.md"
edition.workspace = true
rust-version.workspace = true
publish = false

[lib]
name = "wasmtime"
crate-type = ["staticlib", "cdylib"]
doc = false
test = false
doctest = false

[dependencies]
wasmtime-c-api = { path = '..', package = 'wasmtime-c-api-impl' }

[features]
# WASMTIME_FEATURE_LIST
default = [
  'profiling',
  'wat',
  'wasi',
  'cache',
  'parallel-compilation',
  'async',
  'coredump',
  'addr2line',
  'demangle',
  'threads',
  'gc',
  'gc-drc',
  'gc-null',
  'cranelift',
  'winch',
  # ... if you add a line above this be sure to change the other locations
  # marked WASMTIME_FEATURE_LIST
]
async = ['wasmtime-c-api/async']
profiling = ["wasmtime-c-api/profiling"]
cache = ["wasmtime-c-api/cache"]
parallel-compilation = ['wasmtime-c-api/parallel-compilation']
wasi = ['wasmtime-c-api/wasi']
logging = ['wasmtime-c-api/logging']
disable-logging = ["wasmtime-c-api/disable-logging"]
coredump = ["wasmtime-c-api/coredump"]
addr2line = ["wasmtime-c-api/addr2line"]
demangle = ["wasmtime-c-api/demangle"]
wat = ["wasmtime-c-api/wat"]
threads = ["wasmtime-c-api/threads"]
gc = ["wasmtime-c-api/gc"]
gc-drc = ["wasmtime-c-api/gc-drc"]
gc-null = ["wasmtime-c-api/gc-null"]
cranelift = ["wasmtime-c-api/cranelift"]
winch = ["wasmtime-c-api/winch"]
# ... if you add a line above this be sure to read the comment at the end of
# `default`
