[package]
name = "cranelift-assembler-x64-meta"
description = "Generate a Cranelift-specific assembler for x64 instructions"
version = "0.124.0"
license = "Apache-2.0 WITH LLVM-exception"
edition.workspace = true
rust-version.workspace = true

[dependencies]
cranelift-srcgen = { workspace = true }

[lints]
workspace = true
