[package]
name = "wasmtime-interface-types"
version = "0.7.0"
authors = ["The Wasmtime Project Developers"]
description = "Support for wasm interface types with wasmtime"
license = "Apache-2.0 WITH LLVM-exception"
categories = ["wasm"]
keywords = ["webassembly", "wasm"]
repository = "https://github.com/bytecodealliance/wasmtime"
readme = "README.md"
edition = "2018"

[dependencies]
anyhow = "1.0.19"
walrus = "0.13"
wasmparser = { version = "0.44.0", default-features = false }
wasm-webidl-bindings = "0.6"
wasmtime = { path = '../api' }
wasmtime-jit = { path = '../jit' }
wasmtime-environ = { path = '../environ' }
wasmtime-runtime = { path = '../runtime' }
wasmtime-wasi = { path = '../wasi' }

[badges]
maintenance = { status = "actively-developed" }
