[package]
name = "cranelift-simplejit"
version = "0.67.0"
authors = ["The Cranelift Project Developers"]
description = "A simple JIT library backed by Cranelift"
repository = "https://github.com/bytecodealliance/wasmtime"
documentation = "https://docs.rs/cranelift-simplejit"
license = "Apache-2.0 WITH LLVM-exception"
readme = "README.md"
edition = "2018"

[dependencies]
cranelift-module = { path = "../module", version = "0.67.0" }
cranelift-native = { path = "../native", version = "0.67.0" }
cranelift-codegen = { path = "../codegen", version = "0.67.0", default-features = false, features = ["std"] }
region = "2.2.0"
libc = { version = "0.2.42" }
errno = "0.2.4"
target-lexicon = "0.11"
memmap = { version = "0.7.0", optional = true }

[target.'cfg(target_os = "windows")'.dependencies]
winapi = { version = "0.3", features = ["winbase", "memoryapi"] }

[features]
selinux-fix = ['memmap']
default = []

[dev-dependencies]
cranelift = { path = "../umbrella", version = "0.67.0" }
cranelift-frontend = { path = "../frontend", version = "0.67.0" }
cranelift-entity = { path = "../entity", version = "0.67.0" }

[badges]
maintenance = { status = "experimental" }
