[package]
authors = ["The Cranelift Project Developers"]
name = "cranelift-frontend"
version = "0.90.0"
description = "Cranelift IR builder helper"
license = "Apache-2.0 WITH LLVM-exception"
documentation = "https://docs.rs/cranelift-frontend"
categories = ["no-std"]
repository = "https://github.com/bytecodealliance/wasmtime"
readme = "README.md"
edition.workspace = true

[dependencies]
cranelift-codegen = { workspace = true, default-features = false }
target-lexicon = { workspace = true }
log = { workspace = true }
hashbrown = { workspace = true, optional = true }
smallvec = { workspace = true }

[features]
default = ["std"]
std = ["cranelift-codegen/std"]
core = ["hashbrown", "cranelift-codegen/core"]

[badges]
maintenance = { status = "experimental" }
