[package]
name = "wasmtime-wiggle"
version = "0.27.0"
authors = ["Pat Hickey <phickey@fastly.com>", "Jakub Konka <kubkonk@jakubkonka.com>", "Alex Crichton <alex@alexcrichton.com>"]
edition = "2018"
license = "Apache-2.0 WITH LLVM-exception"
description = "Integrate Wiggle code generator with Wasmtime"
categories = ["wasm"]
keywords = ["webassembly", "wasm"]
repository = "https://github.com/bytecodealliance/wasmtime"
include = ["src/**/*", "LICENSE"]

[dependencies]
wasmtime = { path = "../../wasmtime", version = "0.27.0", default-features = false }
wasmtime-wiggle-macro = { path = "./macro", version = "0.27.0" }
witx = { version = "0.9.0", path = "../../wasi-common/WASI/tools/witx", optional = true }
wiggle = { path = "..", version = "0.27.0" }
wiggle-borrow = { path = "../borrow", version = "0.27.0" }

[dev-dependencies]
anyhow = "1"
proptest = "1.0.0"

[[test]]
name = "atoms_async"
path = "tests/atoms_async.rs"
required-features = ["async", "wasmtime/wat"]

[[test]]
name = "atoms_sync"
path = "tests/atoms_sync.rs"
required-features = ["wasmtime/wat"]

[badges]
maintenance = { status = "actively-developed" }

[features]
# Async support for wasmtime
async = [ 'wasmtime/async', 'wasmtime-wiggle-macro/async' ]

# The wiggle proc-macro emits some code (inside `pub mod metadata`) guarded
# by the `wiggle_metadata` feature flag. We use this feature flag so that
# users of wiggle are not forced to take a direct dependency on the `witx`
# crate unless they want it.
wiggle_metadata = ['witx', "wiggle/wiggle_metadata"]

# The `tracing` crate can use the `log` ecosystem of backends with this
# non-default feature. We don't need to provide this by default, but its
# useful for users that don't want to use `tracing-subscriber` to get
# the logs out of wiggle-generated libraries.
tracing_log = [ "wiggle/tracing_log" ]

default = ["wiggle_metadata", "async"]
