[package]
name = "wasi-nn-example"
version = "0.0.0"
authors = ["The Wasmtime Project Developers"]
readme = "README.md"
edition = "2021"
publish = false

[dependencies]
wasi-nn = "0.1.0"

# This crate is built with the wasm32-wasip1 target, so it's separate
# from the main Wasmtime build, so use this directive to exclude it
# from the parent directory's workspace.
[workspace]
