[package]
name = "cranelift-object"
version = "0.90.0"
authors = ["The Cranelift Project Developers"]
description = "Emit Cranelift output to native object files with `object`"
repository = "https://github.com/bytecodealliance/wasmtime"
documentation = "https://docs.rs/cranelift-object"
license = "Apache-2.0 WITH LLVM-exception"
readme = "README.md"
edition.workspace = true

[dependencies]
cranelift-module = { workspace = true }
cranelift-codegen = { workspace = true, default-features = false, features = ["std"] }
object = { workspace = true, features = ["write"] }
target-lexicon = { workspace = true }
anyhow = { workspace = true }
log = { workspace = true }

[dev-dependencies]
cranelift-frontend = { workspace = true }
cranelift-entity = { workspace = true }

[badges]
maintenance = { status = "experimental" }
