[package]
name = "cranelift-object"
version = "0.46.0"
authors = ["The Cranelift Project Developers"]
description = "Emit Cranelift output to native object files with `object`"
repository = "https://github.com/CraneStation/cranelift"
documentation = "https://cranelift.readthedocs.io/"
license = "Apache-2.0 WITH LLVM-exception"
readme = "README.md"
edition = "2018"

[dependencies]
cranelift-codegen = { path = "../cranelift-codegen", version = "0.46.0" }
cranelift-module = { path = "../cranelift-module", version = "0.46.0" }
object = { version = "0.14.0", default-features = false, features = ["write"] }
target-lexicon = "0.8.1"

[badges]
maintenance = { status = "experimental" }
travis-ci = { repository = "CraneStation/cranelift" }
