[package]
name = "wasi-preview1-component-adapter"
version = "23.0.0+wasi-0.2.0"
rust-version = "1.77.0"
authors.workspace = true
edition.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
wasi = { version = "0.11.0", default-features = false }
wit-bindgen-rust-macro = { workspace = true }
byte-array-literals = { workspace = true }
bitflags = { workspace = true }

[build-dependencies]
wasm-encoder = { workspace = true }
object = { workspace = true, default-features = false, features = ["archive", "std"] }

[lib]
test = false
crate-type = ["cdylib"]
name = "wasi_snapshot_preview1"
doc = false

[features]
default = ["reactor"]
reactor = []
command = []
proxy = []
