[package]
name = "peepmatic-automata"
version = "0.78.0"
authors = ["Nick Fitzgerald <fitzgen@gmail.com>"]
edition = "2018"
license = "Apache-2.0 WITH LLVM-exception"
description = "Finite-state transducer automata"

# FIXME(rust-lang/cargo#9300): uncomment once that lands
# [package.metadata.docs.rs]
# all-features = true

[dependencies]
serde = { version = "1.0.106", optional = true }

[features]
# Enable support for generating GraphViz Dot files that can be used to visually
# render an automaton.
#
# https://en.wikipedia.org/wiki/DOT_%28graph_description_language%29
dot = []
