[package]
name = "component-test-util"
authors = ["The Wasmtime Project Developers"]
license = "Apache-2.0 WITH LLVM-exception"
version = "0.0.0"
edition.workspace = true
publish = false

[dependencies]
env_logger = { workspace = true }
anyhow = { workspace = true }
arbitrary = { version = "1.1.0", features = ["derive"] }
wasmtime = { workspace = true, features = ["component-model", "async"] }
