[package]
name = "wasmtime-fuzz"
version = "0.7.0"
authors = ["The Wasmtime Project Developers"]
edition = "2018"
publish = false

[package.metadata]
cargo-fuzz = true

[dependencies]
wasmtime-environ = { path = "../crates/environ" }
wasmtime-jit = { path = "../crates/jit" }
cranelift-codegen = "0.50"
cranelift-wasm = "0.50"
cranelift-native = "0.50"
libfuzzer-sys = { git = "https://github.com/rust-fuzz/libfuzzer-sys.git" }
wasmparser = { version = "0.39.2", default-features = false, features = ["core"] }
binaryen = "0.8.1"

# Prevent this from interfering with workspaces
[workspace]
members = ["."]

[[bin]]
name = "compile"
path = "fuzz_targets/compile.rs"

[[bin]]
name = "instantiate"
path = "fuzz_targets/instantiate.rs"

[[bin]]
name = "instantiate_translated"
path = "fuzz_targets/instantiate_translated.rs"
