[package]
name = "wasmtime-fuzz"
version = "0.12.0"
authors = ["The Wasmtime Project Developers"]
edition = "2018"
publish = false

[package.metadata]
cargo-fuzz = true

[dependencies]
cranelift-codegen = { path = "../cranelift/codegen" }
cranelift-reader = { path = "../cranelift/reader" }
cranelift-wasm = { path = "../cranelift/wasm" }
libfuzzer-sys = "0.3.1"
target-lexicon = "0.10"
wasmtime = { path = "../crates/api" }
wasmtime-fuzzing = { path = "../crates/fuzzing" }

[[bin]]
name = "compile"
path = "fuzz_targets/compile.rs"
test = false
doc = false

[[bin]]
name = "instantiate"
path = "fuzz_targets/instantiate.rs"
test = false
doc = false

[[bin]]
name = "instantiate_translated"
path = "fuzz_targets/instantiate_translated.rs"
test = false
doc = false
required-features = ['binaryen']

[[bin]]
name = "api_calls"
path = "fuzz_targets/api_calls.rs"
test = false
doc = false
required-features = ['binaryen']

[[bin]]
name = "differential"
path = "fuzz_targets/differential.rs"
test = false
doc = false
required-features = ['binaryen']

[features]
binaryen = ['wasmtime-fuzzing/binaryen']
