[package]
name = "test-programs-macros"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
proc-macro = true
doctest = false
test = false

[dependencies]
quote = "1.0"

[build-dependencies]
wit-component = "0.7.0"
cargo_metadata = "0.15.3"
heck = "0.4.0"
