[package]
name = "test-programs-macros"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
proc-macro = true
doctest = false
test = false

[dependencies]
quote = "1.0"

[build-dependencies]
wit-component = { git = "https://github.com/bytecodealliance/wasm-tools", rev = "b17fc48a23152735bafd8f7ee95e3b55683d9511" }
cargo_metadata = "0.15.3"
heck = "0.4.0"
