[package]
name = "cranelift-interpreter"
version = "0.71.0"
authors = ["The Cranelift Project Developers"]
description = "Interpret Cranelift IR"
repository = "https://github.com/bytecodealliance/wasmtime"
documentation = "https://docs.rs/cranelift-interpreter"
categories = ["no-std"]
license = "Apache-2.0 WITH LLVM-exception"
readme = "README.md"
edition = "2018"

[dependencies]
cranelift-codegen = { path = "../codegen", version = "0.71.0", features = ["all-arch"] }
cranelift-entity = { path = "../entity", version = "0.71.0" }
cranelift-reader = { path = "../reader", version = "0.71.0" }
log = { version = "0.4.8", default-features = false }
smallvec = "1.6.1"
thiserror = "1.0.15"

[dev-dependencies]
cranelift-frontend = { path = "../frontend", version = "0.71.0" }

[badges]
maintenance = { status = "experimental" }
