[package]
name = "wasmtime-c-api"
version = "0.19.0"
authors = ["The Wasmtime Project Developers"]
description = "C API to expose the Wasmtime runtime"
license = "Apache-2.0 WITH LLVM-exception"
repository = "https://github.com/bytecodealliance/wasmtime"
readme = "README.md"
edition = "2021"
publish = false

[lib]
name = "wasmtime"
crate-type = ["staticlib", "cdylib"]
doc = false
test = false
doctest = false

[dependencies]
env_logger = "0.9"
anyhow = "1.0"
once_cell = "1.3"
wasmtime = { path = "../wasmtime", default-features = false, features = ['cranelift'] }
wasmtime-c-api-macros = { path = "macros" }

# Optional dependency for the `wat2wasm` API
wat = { version = "1.0.42", optional = true }

# Optional dependencies for the `wasi` feature
wasi-cap-std-sync = { path = "../wasi-common/cap-std-sync", optional = true }
wasmtime-wasi = { path = "../wasi", optional = true }
cap-std = { version = "0.24.1", optional = true }

[features]
default = ['jitdump', 'wat', 'wasi', 'cache']
jitdump = ["wasmtime/jitdump"]
cache = ["wasmtime/cache"]
wasi = ['wasi-cap-std-sync', 'wasmtime-wasi', 'cap-std']
