[package]
name = "wasmtime-c-api"
version = "0.17.0"
authors = ["The Wasmtime Project Developers"]
description = "C API to expose the Wasmtime runtime"
license = "Apache-2.0 WITH LLVM-exception"
repository = "https://github.com/bytecodealliance/wasmtime"
readme = "README.md"
edition = "2018"
publish = false

[lib]
name = "wasmtime"
crate-type = ["staticlib", "cdylib"]
doc = false
test = false
doctest = false

[dependencies]
env_logger = "0.7"
anyhow = "1.0"
once_cell = "1.3"
wasmtime = { path = "../wasmtime", default-features = false }
wasmtime-c-api-macros = { path = "macros" }

# Optional dependency for the `wat2wasm` API
wat = { version = "1.0.18", optional = true }

# Optional dependencies for the `wasi` feature
wasi-common = { path = "../wasi-common", optional = true }
wasmtime-wasi = { path = "../wasi", optional = true }

[features]
default = ['jitdump', 'wat', 'wasi']
lightbeam = ["wasmtime/lightbeam"]
jitdump = ["wasmtime/jitdump"]
wasi = ['wasi-common', 'wasmtime-wasi']
