
# cargo-vet config file

[cargo-vet]
version = "0.10"

[imports.embark-studios]
url = "https://raw.githubusercontent.com/EmbarkStudios/rust-ecosystem/main/audits.toml"

[imports.fermyon]
url = "https://raw.githubusercontent.com/fermyon/spin/main/supply-chain/audits.toml"

[imports.google]
url = [
    "https://chromium.googlesource.com/chromiumos/third_party/rust_crates/+/main/cargo-vet/audits.toml?format=TEXT",
    "https://fuchsia.googlesource.com/fuchsia/+/refs/heads/main/third_party/rust_crates/supply-chain/audits.toml?format=TEXT",
]

[imports.isrg]
url = "https://raw.githubusercontent.com/divviup/libprio-rs/main/supply-chain/audits.toml"

[imports.mozilla]
url = "https://raw.githubusercontent.com/mozilla/supply-chain/main/audits.toml"

[policy.cranelift]
audit-as-crates-io = true

[policy.cranelift-bforest]
audit-as-crates-io = true

[policy.cranelift-bitset]
audit-as-crates-io = true

[policy.cranelift-codegen]
audit-as-crates-io = true

[policy.cranelift-codegen-meta]
audit-as-crates-io = true

[policy.cranelift-codegen-shared]
audit-as-crates-io = true

[policy.cranelift-control]
audit-as-crates-io = true

[policy.cranelift-entity]
audit-as-crates-io = true

[policy.cranelift-frontend]
audit-as-crates-io = true

[policy.cranelift-fuzzgen]
criteria = []

[policy.cranelift-interpreter]
audit-as-crates-io = true

[policy.cranelift-isle]
audit-as-crates-io = true

[policy.cranelift-jit]
audit-as-crates-io = true

[policy.cranelift-module]
audit-as-crates-io = true

[policy.cranelift-native]
audit-as-crates-io = true

[policy.cranelift-object]
audit-as-crates-io = true

[policy.cranelift-reader]
audit-as-crates-io = true

[policy.cranelift-serde]
audit-as-crates-io = true

[policy.isle-fuzz]
criteria = []

[policy.pulley-interpreter]
audit-as-crates-io = true

[policy.pulley-interpreter-fuzz]
criteria = []

[policy.wasi-common]
audit-as-crates-io = true

[policy.wasmtime]
audit-as-crates-io = true

[policy.wasmtime-asm-macros]
audit-as-crates-io = true

[policy.wasmtime-c-api-impl]
audit-as-crates-io = false

[policy.wasmtime-c-api-macros]
audit-as-crates-io = false

[policy.wasmtime-cache]
audit-as-crates-io = true

[policy.wasmtime-cli]
audit-as-crates-io = true

[policy.wasmtime-cli-flags]
audit-as-crates-io = true

[policy.wasmtime-component-macro]
audit-as-crates-io = true

[policy.wasmtime-component-util]
audit-as-crates-io = true

[policy.wasmtime-cranelift]
audit-as-crates-io = true

[policy.wasmtime-environ]
audit-as-crates-io = true

[policy.wasmtime-environ-fuzz]
criteria = []

[policy.wasmtime-explorer]
audit-as-crates-io = true

[policy.wasmtime-fiber]
audit-as-crates-io = true

[policy.wasmtime-fuzz]
criteria = []

[policy.wasmtime-fuzzing]
criteria = []

[policy.wasmtime-jit-debug]
audit-as-crates-io = true

[policy.wasmtime-jit-icache-coherence]
audit-as-crates-io = true

[policy.wasmtime-slab]
audit-as-crates-io = true

[policy.wasmtime-versioned-export-macros]
audit-as-crates-io = false

[policy.wasmtime-wasi]
audit-as-crates-io = true

[policy.wasmtime-wasi-config]
audit-as-crates-io = true

[policy.wasmtime-wasi-http]
audit-as-crates-io = true

[policy.wasmtime-wasi-keyvalue]
audit-as-crates-io = true

[policy.wasmtime-wasi-nn]
audit-as-crates-io = true

[policy.wasmtime-wasi-threads]
audit-as-crates-io = true

[policy.wasmtime-wast]
audit-as-crates-io = true

[policy.wasmtime-winch]
audit-as-crates-io = true

[policy.wasmtime-wit-bindgen]
audit-as-crates-io = true

[policy.wasmtime-wmemcheck]
audit-as-crates-io = true

[policy.wiggle]
audit-as-crates-io = true

[policy.wiggle-generate]
audit-as-crates-io = true

[policy.wiggle-macro]
audit-as-crates-io = true

[policy.wiggle-test]
audit-as-crates-io = true

[policy.winch-codegen]
audit-as-crates-io = true

[[exemptions.addr2line]]
version = "0.17.0"
criteria = "safe-to-deploy"

[[exemptions.aes]]
version = "0.8.4"
criteria = "safe-to-deploy"

[[exemptions.ahash]]
version = "0.8.11"
criteria = "safe-to-deploy"

[[exemptions.base64ct]]
version = "1.6.0"
criteria = "safe-to-deploy"

[[exemptions.bitflags]]
version = "1.3.2"
criteria = "safe-to-deploy"

[[exemptions.capstone]]
version = "0.12.0"
criteria = "safe-to-deploy"

[[exemptions.capstone-sys]]
version = "0.16.0"
criteria = "safe-to-deploy"

[[exemptions.console]]
version = "0.15.0"
criteria = "safe-to-deploy"

[[exemptions.constant_time_eq]]
version = "0.1.5"
criteria = "safe-to-deploy"

[[exemptions.cpp_demangle]]
version = "0.3.5"
criteria = "safe-to-deploy"

[[exemptions.cpufeatures]]
version = "0.2.2"
criteria = "safe-to-deploy"

[[exemptions.crc32fast]]
version = "1.3.2"
criteria = "safe-to-deploy"

[[exemptions.criterion]]
version = "0.3.5"
criteria = "safe-to-run"

[[exemptions.criterion-plot]]
version = "0.4.4"
criteria = "safe-to-run"

[[exemptions.crossbeam-deque]]
version = "0.8.1"
criteria = "safe-to-deploy"

[[exemptions.crossbeam-epoch]]
version = "0.9.9"
criteria = "safe-to-deploy"

[[exemptions.crossbeam-utils]]
version = "0.8.10"
criteria = "safe-to-deploy"

[[exemptions.digest]]
version = "0.9.0"
criteria = "safe-to-deploy"

[[exemptions.directories-next]]
version = "2.0.0"
criteria = "safe-to-deploy"

[[exemptions.dirs-sys-next]]
version = "0.1.2"
criteria = "safe-to-deploy"

[[exemptions.encode_unicode]]
version = "0.3.6"
criteria = "safe-to-deploy"

[[exemptions.fallible-iterator]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.futures-task]]
version = "0.3.27"
criteria = "safe-to-deploy"
notes = "deferring this vetting until Alex gets back from vacation"

[[exemptions.futures-util]]
version = "0.3.27"
criteria = "safe-to-deploy"
notes = "this is 25k lines and contains over 149 uses of the substring unsafe. it is a huge grab bag of complexity with no practical way to audit it"

[[exemptions.generic-array]]
version = "0.14.5"
criteria = "safe-to-deploy"

[[exemptions.getrandom]]
version = "0.2.6"
criteria = "safe-to-deploy"

[[exemptions.gimli]]
version = "0.26.1"
criteria = "safe-to-deploy"

[[exemptions.h2]]
version = "0.4.4"
criteria = "safe-to-deploy"

[[exemptions.half]]
version = "2.4.1"
criteria = "safe-to-deploy"

[[exemptions.hermit-abi]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.http]]
version = "0.2.9"
criteria = "safe-to-deploy"
notes = "we are exempting tokio, hyper, and their tightly coupled dependencies by the same authors, expecting that the authors at aws will publish attestions we can import at some point soon"

[[exemptions.httparse]]
version = "1.8.0"
criteria = "safe-to-deploy"
notes = "we are exempting tokio, hyper, and their tightly coupled dependencies by the same authors, expecting that the authors at aws will publish attestions we can import at some point soon"

[[exemptions.humantime]]
version = "2.1.0"
criteria = "safe-to-deploy"

[[exemptions.hyper]]
version = "1.0.0-rc.3"
criteria = "safe-to-deploy"
notes = "we are exempting tokio, hyper, and their tightly coupled dependencies by the same authors, expecting that the authors at aws will publish attestions we can import at some point soon"

[[exemptions.indicatif]]
version = "0.13.0"
criteria = "safe-to-deploy"

[[exemptions.ipnet]]
version = "2.5.0"
criteria = "safe-to-deploy"

[[exemptions.itertools]]
version = "0.10.3"
criteria = "safe-to-deploy"

[[exemptions.libloading]]
version = "0.7.3"
criteria = "safe-to-deploy"

[[exemptions.listenfd]]
version = "1.0.0"
criteria = "safe-to-deploy"

[[exemptions.logos]]
version = "0.14.2"
criteria = "safe-to-deploy"
notes = "safe when forbid_unsafe feature enabled, which it is in our dep through wasm-wave"

[[exemptions.logos-codegen]]
version = "0.14.2"
criteria = "safe-to-deploy"
notes = "safe when forbid_unsafe feature enabled, which it is in our dep through wasm-wave"

[[exemptions.logos-derive]]
version = "0.14.2"
criteria = "safe-to-deploy"
notes = "safe when forbid_unsafe feature enabled, which it is in our dep through wasm-wave"

[[exemptions.matrixmultiply]]
version = "0.3.9"
criteria = "safe-to-deploy"

[[exemptions.maybe-owned]]
version = "0.3.4"
criteria = "safe-to-deploy"

[[exemptions.memmap2]]
version = "0.2.3"
criteria = "safe-to-deploy"

[[exemptions.mio]]
version = "0.8.11"
criteria = "safe-to-deploy"

[[exemptions.ndarray]]
version = "0.15.6"
criteria = "safe-to-deploy"

[[exemptions.num-complex]]
version = "0.4.6"
criteria = "safe-to-deploy"

[[exemptions.num_cpus]]
version = "1.13.1"
criteria = "safe-to-deploy"

[[exemptions.number_prefix]]
version = "0.3.0"
criteria = "safe-to-deploy"

[[exemptions.object]]
version = "0.36.0"
criteria = "safe-to-deploy"

[[exemptions.once_cell]]
version = "1.12.0"
criteria = "safe-to-deploy"

[[exemptions.openvino-finder]]
version = "0.4.1"
criteria = "safe-to-deploy"

[[exemptions.openvino-sys]]
version = "0.4.1"
criteria = "safe-to-deploy"

[[exemptions.password-hash]]
version = "0.4.2"
criteria = "safe-to-deploy"

[[exemptions.pbkdf2]]
version = "0.11.0"
criteria = "safe-to-deploy"

[[exemptions.ppv-lite86]]
version = "0.2.16"
criteria = "safe-to-deploy"

[[exemptions.pretty_env_logger]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.proptest]]
version = "1.0.0"
criteria = "safe-to-deploy"

[[exemptions.psm]]
version = "0.1.18"
criteria = "safe-to-deploy"

[[exemptions.quick-error]]
version = "1.2.3"
criteria = "safe-to-deploy"

[[exemptions.quick-error]]
version = "2.0.1"
criteria = "safe-to-deploy"

[[exemptions.rand]]
version = "0.8.5"
criteria = "safe-to-deploy"

[[exemptions.rand_xorshift]]
version = "0.3.0"
criteria = "safe-to-deploy"

[[exemptions.rawpointer]]
version = "0.2.1"
criteria = "safe-to-deploy"

[[exemptions.redox_syscall]]
version = "0.2.13"
criteria = "safe-to-deploy"

[[exemptions.redox_users]]
version = "0.4.3"
criteria = "safe-to-deploy"

[[exemptions.region]]
version = "2.2.0"
criteria = "safe-to-deploy"

[[exemptions.ring]]
version = "0.17.3"
criteria = "safe-to-deploy"

[[exemptions.rustls]]
version = "0.22.4"
criteria = "safe-to-deploy"

[[exemptions.rustls-pki-types]]
version = "1.3.1"
criteria = "safe-to-deploy"

[[exemptions.rustls-webpki]]
version = "0.102.2"
criteria = "safe-to-deploy"

[[exemptions.rusty-fork]]
version = "0.3.0"
criteria = "safe-to-deploy"

[[exemptions.shellexpand]]
version = "2.1.0"
criteria = "safe-to-deploy"

[[exemptions.shuffling-allocator]]
version = "1.1.2"
criteria = "safe-to-deploy"

[[exemptions.slice-group-by]]
version = "0.3.0"
criteria = "safe-to-deploy"

[[exemptions.smallvec]]
version = "1.8.0"
criteria = "safe-to-deploy"

[[exemptions.socket2]]
version = "0.4.9"
criteria = "safe-to-deploy"

[[exemptions.souper-ir]]
version = "2.1.0"
criteria = "safe-to-deploy"

[[exemptions.spin]]
version = "0.9.4"
criteria = "safe-to-deploy"

[[exemptions.stable_deref_trait]]
version = "1.2.0"
criteria = "safe-to-deploy"

[[exemptions.strsim]]
version = "0.10.0"
criteria = "safe-to-deploy"

[[exemptions.tempfile]]
version = "3.3.0"
criteria = "safe-to-deploy"

[[exemptions.terminal_size]]
version = "0.1.17"
criteria = "safe-to-deploy"

[[exemptions.time]]
version = "0.3.36"
criteria = "safe-to-deploy"

[[exemptions.tokio]]
version = "1.30.0"
criteria = "safe-to-deploy"
notes = "we are exempting tokio, hyper, and their tightly coupled dependencies by the same authors, expecting that the authors at aws will publish attestions we can import at some point soon"

[[exemptions.tokio-macros]]
version = "1.7.0"
criteria = "safe-to-deploy"

[[exemptions.tokio-rustls]]
version = "0.25.0"
criteria = "safe-to-deploy"

[[exemptions.tracing-attributes]]
version = "0.1.21"
criteria = "safe-to-deploy"

[[exemptions.tracing-core]]
version = "0.1.28"
criteria = "safe-to-deploy"

[[exemptions.typenum]]
version = "1.15.0"
criteria = "safe-to-deploy"

[[exemptions.untrusted]]
version = "0.9.0"
criteria = "safe-to-deploy"

[[exemptions.ureq]]
version = "2.9.6"
criteria = "safe-to-deploy"

[[exemptions.uuid]]
version = "1.0.0"
criteria = "safe-to-deploy"

[[exemptions.wait-timeout]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.webpki-roots]]
version = "0.26.1"
criteria = "safe-to-deploy"

[[exemptions.winapi]]
version = "0.3.9"
criteria = "safe-to-deploy"

[[exemptions.winapi-i686-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.winapi-x86_64-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.zeroize]]
version = "1.7.0"
criteria = "safe-to-deploy"

[[exemptions.zip]]
version = "0.6.6"
criteria = "safe-to-deploy"

[[exemptions.zstd]]
version = "0.11.1+zstd.1.5.2"
criteria = "safe-to-deploy"

[[exemptions.zstd]]
version = "0.11.2+zstd.1.5.2"
criteria = "safe-to-deploy"

[[exemptions.zstd-safe]]
version = "5.0.1+zstd.1.5.2"
criteria = "safe-to-deploy"

[[exemptions.zstd-safe]]
version = "5.0.2+zstd.1.5.2"
criteria = "safe-to-deploy"

[[exemptions.zstd-sys]]
version = "2.0.9+zstd.1.5.5"
criteria = "safe-to-deploy"
