[package]
name = "wasi-c2"
version = "0.22.0"
authors = ["The Wasmtime Project Developers"]
description = "WASI implementation in Rust"
license = "Apache-2.0 WITH LLVM-exception"
categories = ["wasm"]
keywords = ["webassembly", "wasm"]
repository = "https://github.com/bytecodealliance/wasmtime"
readme = "README.md"
edition = "2018"
include = ["src/**/*", "LICENSE", "build.rs"]
build = "build.rs"
publish = false

# This doesn't actually link to a native library, but it allows us to set env
# vars like `DEP_WASI_C2_19_*` for crates that have build scripts and depend
# on this crate, allowing other crates to use the same witx files.
links = "wasi-c2-19"

[dependencies]
anyhow = "1.0"
thiserror = "1.0"
libc = "0.2"
wiggle = { path = "../wiggle", default-features = false, version = "0.22.0" }
tracing = "0.1.19"
system-interface = "0.2"
cap-std = "0.9"
cap-fs-ext = "0.9"
cap-time-ext = "0.9"
cap-rand = "0.9"
fs-set-times = "0.2.2"
cfg-if = "1"
bitflags = "1.2"

[badges]
maintenance = { status = "actively-developed" }

[features]
default = ["trace_log"]
# This feature enables the `tracing` logs in the calls to target the `log`
# ecosystem of backends (e.g. `env_logger`. Disable this if you want to use
# `tracing-subscriber`.
trace_log = [ "wiggle/tracing_log", "tracing/log" ]
# Need to make the wiggle_metadata feature available to consumers of this
# crate if they want the snapshots to have metadata available.
wiggle_metadata = ["wiggle/wiggle_metadata"]
