[package]
name = "cranelift-faerie"
version = "0.59.0"
authors = ["The Cranelift Project Developers"]
description = "Emit Cranelift output to native object files with Faerie"
repository = "https://github.com/bytecodealliance/cranelift"
documentation = "https://docs.rs/cranelift-faerie"
license = "Apache-2.0 WITH LLVM-exception"
readme = "README.md"
edition = "2018"

[dependencies]
cranelift-module = { path = "../module", version = "0.59.0" }
faerie = "0.14.0"
goblin = "0.1.0"
anyhow = "1.0"
target-lexicon = "0.10"

[dependencies.cranelift-codegen]
path = "../codegen"
version = "0.59.0"
default-features = false
features = ["std"]

[badges]
maintenance = { status = "experimental" }
travis-ci = { repository = "bytecodealliance/cranelift" }
