[package]
name = "cranelift-faerie"
version = "0.49.0"
authors = ["The Cranelift Project Developers"]
description = "Emit Cranelift output to native object files with Faerie"
repository = "https://github.com/bytecodealliance/cranelift"
documentation = "https://cranelift.readthedocs.io/"
license = "Apache-2.0 WITH LLVM-exception"
readme = "README.md"
edition = "2018"

[dependencies]
cranelift-module = { path = "../cranelift-module", version = "0.49.0" }
faerie = "0.12.0"
goblin = "0.1.0"
failure = "0.1.2"
target-lexicon = "0.9"

[dependencies.cranelift-codegen]
path = "../cranelift-codegen"
version = "0.49.0"
default-features = false
features = ["std"]

[badges]
maintenance = { status = "experimental" }
travis-ci = { repository = "bytecodealliance/cranelift" }
