[package]
name = "wasmtime-explorer"
authors.workspace = true
description = "Compiler explorer for Wasmtime and Cranelift"
documentation = "https://docs.rs/wasmtime-explorer/"
edition.workspace = true
rust-version.workspace = true
license = "Apache-2.0 WITH LLVM-exception"
repository = "https://github.com/bytecodealliance/wasmtime"
version.workspace = true

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
capstone = { workspace = true }
serde = { workspace = true }
serde_derive = { workspace = true }
serde_json = { workspace = true }
target-lexicon = { workspace = true, features = ['std'] }
wasmprinter = { workspace = true }
wasmtime = { workspace = true, features = ["cranelift", "runtime"] }
wasmtime-environ = { workspace = true }
