[package]
name = "wasmtime-wiggle-macro"
version = "0.23.0"
authors = ["Pat Hickey <phickey@fastly.com>", "Jakub Konka <kubkonk@jakubkonka.com>", "Alex Crichton <alex@alexcrichton.com>"]
edition = "2018"
license = "Apache-2.0 WITH LLVM-exception"
description = "Macro for integrating Wiggle code generator with Wasmtime"
categories = ["wasm"]
keywords = ["webassembly", "wasm"]
repository = "https://github.com/bytecodealliance/wasmtime"
include = ["src/**/*", "LICENSE"]

[lib]
proc-macro = true
test = false

[dependencies]
witx = { version = "0.9", path = "../../../wasi-common/WASI/tools/witx" }
wiggle-generate = { path = "../../generate", version = "0.23.0" }
quote = "1.0"
syn = { version = "1.0", features = ["full", "extra-traits"]  }
proc-macro2 = "1.0"

[badges]
maintenance = { status = "actively-developed" }

[features]
async = []
default = []
