[package]
name = "peepmatic"
version = "0.66.0"
authors = ["Nick Fitzgerald <fitzgen@gmail.com>"]
edition = "2018"
license = "Apache-2.0 WITH LLVM-exception"
description = "DSL and compiler for generating peephole optimizers"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.27"
peepmatic-automata = { version = "0.2.0", path = "crates/automata", features = ["dot"] }
peepmatic-macro = { version = "0.2.0", path = "crates/macro" }
peepmatic-runtime = { version = "0.2.0", path = "crates/runtime", features = ["construct"] }
wast = "15.0.0"
z3 = { version = "0.6.0", features = ["static-link-z3"] }
