[package]
name = "embedding"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }

# Note that default-features of wasmtime are disabled and only those required
# are enabled, in this case compilation is done in the guest from the wasm text
# format so `cranelift` and `wat` are enabled.
wasmtime = { workspace = true, features = ['runtime'] }

# Memory allocator used in this example (not required, however)
dlmalloc = "0.2.4"

[lib]
crate-type = ['staticlib']
test = false
doctest = false

[features]
custom = ['wasmtime/custom-virtual-memory', 'wasmtime/custom-native-signals']
