[package]
authors = ["The Wasmtime Project Developers"]
description = "Macros for defining asm functions in Wasmtime"
edition.workspace = true
license = "Apache-2.0 WITH LLVM-exception"
name = "wasmtime-asm-macros"
repository = "https://github.com/bytecodealliance/wasmtime"
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cfg-if = "1"
