[package]
name = "wasi-cap-std-sync"
version.workspace = true
authors.workspace = true
description = "WASI implementation in Rust"
license = "Apache-2.0 WITH LLVM-exception"
categories = ["wasm"]
keywords = ["webassembly", "wasm"]
repository = "https://github.com/bytecodealliance/wasmtime"
readme = "README.md"
edition.workspace = true
include = ["src/**/*", "README.md", "LICENSE" ]

[dependencies]
wasi-common = { workspace = true }
async-trait = { workspace = true }
anyhow = { workspace = true }
cap-std = { workspace = true }
cap-fs-ext = { workspace = true }
cap-net-ext = { workspace = true }
cap-time-ext = "1.0.0"
cap-rand = { workspace = true }
fs-set-times = "0.19.0"
system-interface = { workspace = true }
tracing = { workspace = true }
io-lifetimes = { workspace = true }
is-terminal = "0.4.0"
io-extras = "0.17.1"
ipnet = { workspace = true }

[target.'cfg(unix)'.dependencies]
rustix = { workspace = true, features = ["fs"] }

[target.'cfg(windows)'.dependencies]
once_cell = { workspace = true }
rustix = { workspace = true, features = ["net"] }

[target.'cfg(windows)'.dependencies.windows-sys]
workspace = true
features = [
    "Win32_Foundation",
]

[dev-dependencies]
tempfile = "3.1.0"
