[package]
name = "wasi-tokio"
version = "0.33.0"
authors = ["The Wasmtime Project Developers"]
description = "WASI implementation in Rust"
license = "Apache-2.0 WITH LLVM-exception"
categories = ["wasm"]
keywords = ["webassembly", "wasm"]
repository = "https://github.com/bytecodealliance/wasmtime"
edition = "2018"
include = ["src/**/*", "LICENSE" ]

[dependencies]
wasi-common = { path = "../", version = "=0.33.0" }
wasi-cap-std-sync = { path = "../cap-std-sync", version = "=0.33.0" }
wiggle = { path = "../../wiggle", version = "=0.33.0" }
tokio = { version = "1.8.0", features = [ "rt", "fs", "time", "io-util", "net", "io-std", "rt-multi-thread"] }
cap-std = "0.22.0"
anyhow = "1"
io-lifetimes = { version = "0.4.4", default-features = false }

[target.'cfg(unix)'.dependencies]
rustix = "0.31.0"

[target.'cfg(windows)'.dependencies]
winapi = "0.3"
lazy_static = "1.4"
io-extras = "0.12.0"

[dev-dependencies]
tempfile = "3.1.0"
tokio = { version = "1.8.0", features = [ "macros" ] }
anyhow = "1"
cap-tempfile = "0.22.0"
