[package]
name = "islec"
version = "0.1.0"
authors = ["Chris Fallin <chris@cfallin.org>"]
edition = "2018"
license = "Apache-2.0 WITH LLVM-exception"

[dependencies]
log = "0.4"
isle = { version = "*", path = "../isle/" }
env_logger = { version = "0.8", default-features = false }
clap = "2.33"
