[package]
name = "islec"
version = "0.1.0"
authors = ["The Cranelift Project Developers"]
edition = "2018"
license = "Apache-2.0 WITH LLVM-exception"
publish = false

[dependencies]
log = "0.4"
isle = { version = "*", path = "../isle/" }
env_logger = { version = "0.8", default-features = false }
miette = { version = "3.0.0", features = ["fancy"] }
structopt = "0.3.23"
