[package]
name = "islec"
version = "0.0.0"
authors = ["The Cranelift Project Developers"]
edition.workspace = true
rust-version.workspace = true
license = "Apache-2.0 WITH LLVM-exception"
publish = false

[dependencies]
cranelift-isle = { version = "*", path = "../isle/", features = ["fancy-errors", "logging"] }
env_logger = { workspace = true }
clap = { workspace = true, features = ['default'] }
