[package]
name = "peepmatic-runtime"
version = "0.78.0"
authors = ["Nick Fitzgerald <fitzgen@gmail.com>"]
edition = "2018"
license = "Apache-2.0 WITH LLVM-exception"
description = "Runtime support for peepmatic peephole optimizers"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1.2.1"
log = "0.4.8"
peepmatic-automata = { version = "=0.78.0", path = "../automata", features = ["serde"] }
peepmatic-traits = { version = "=0.78.0", path = "../traits" }
serde = { version = "1.0.105", features = ["derive"] }
thiserror = "1.0.15"
wast = { version = "38.0.0", optional = true }

[dev-dependencies]
peepmatic-test-operator = { path = "../test-operator" }
serde_test = "1.0.114"

[features]
# Enable support for a few extra methods that are required by the `peepmatic`
# crate when constructing peephole optimizers, but are not needed when simply
# using already-constructed peephole optimizers.
construct = ["wast"]
