[package]
name = "peepmatic-test-operator"
description = "Operator for usage in peepmatic tests"
license = "Apache-2.0 WITH LLVM-exception"
version = "0.76.0"
authors = ["Nick Fitzgerald <fitzgen@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
peepmatic-traits = { version = "0.76.0", path = "../traits" }
serde = { version = "1.0.105", features = ["derive"] }
wast = "36.0.0"
