[package]
name = "wasmtime-jit-debug"
version = "0.35.0"
authors = ["The Wasmtime Project Developers"]
description = "JIT debug interfaces support for Wasmtime"
license = "Apache-2.0 WITH LLVM-exception"
categories = ["development-tools::debugging"]
keywords = ["gdb", "jit"]
repository = "https://github.com/bytecodealliance/wasmtime"
readme = "README.md"
edition = "2018"

[dependencies]
lazy_static = {version = "1.3.0", optional = true }
object = { version = "0.27.0", default-features = false, features = ["std", "read_core"], optional = true }

[target.'cfg(target_os = "linux")'.dependencies]
rustix = { version = "0.33.5", optional = true }

[badges]
maintenance = { status = "actively-developed" }

[features]
gdb_jit_int = ["lazy_static"]
perf_jitdump = ["rustix", "object"]
