[package]
name = "wasmtime-jit-debug"
version = "0.40.0"
authors = ["The Wasmtime Project Developers"]
description = "JIT debug interfaces support for Wasmtime"
license = "Apache-2.0 WITH LLVM-exception"
categories = ["development-tools::debugging"]
keywords = ["gdb", "jit"]
repository = "https://github.com/bytecodealliance/wasmtime"
readme = "README.md"
edition = "2021"

[dependencies]
once_cell = {version = "1.12.0", optional = true }
object = { version = "0.28.0", default-features = false, features = ["std", "read_core"], optional = true }

[target.'cfg(target_os = "linux")'.dependencies]
rustix = { version = "0.35.6", features = ["mm", "param", "time"], optional = true }

[badges]
maintenance = { status = "actively-developed" }

[features]
gdb_jit_int = ["once_cell"]
perf_jitdump = ["rustix", "object"]
