[package]
name = "wasi-nn-example-winml"
version = "0.0.0"
authors = ["The Wasmtime Project Developers"]
readme = "README.md"
edition = "2021"
publish = false

[dependencies]
wasi-nn = "0.6.0"
image = { version = "0.24.6", default-features = false, features = ["png"] }
ndarray = "0.15.3"

# This crate is built with the wasm32-wasi target, so it's separate
# from the main Wasmtime build, so use this directive to exclude it
# from the parent directory's workspace.
[workspace]
