[package]
name = "wasmtime-wasi-c"
version = "0.2.0"
authors = ["The Cranelift Project Developers"]
description = "WASI API support for Wasmtime"
license = "Apache-2.0 WITH LLVM-exception"
categories = ["wasm"]
keywords = ["webassembly", "wasm"]
repository = "https://github.com/bytecodealliance/wasmtime"
readme = "README.md"
edition = "2018"

[dependencies]
wasmtime-runtime = { path = "../runtime" }
wasmtime-environ = { path = "../environ" }
wasmtime-jit = { path = "../jit" }
cranelift-codegen = { version = "0.50.0", features = ["enable-serde"] }
cranelift-entity = { version = "0.50.0", features = ["enable-serde"] }
cranelift-wasm = { version = "0.50.0", features = ["enable-serde"] }
target-lexicon = "0.9.0"
log = { version = "0.4.8", default-features = false }
libc = "0.2.60"
more-asserts = "0.2.1"

[build-dependencies]
cmake = "0.1.35"
bindgen = "0.51.0"

[badges]
maintenance = { status = "actively-developed" }
