[package]
name = "wasmtime-cli-flags"
version.workspace = true
authors.workspace = true
description = "Exposes common CLI flags used for running Wasmtime"
license = "Apache-2.0 WITH LLVM-exception"
repository = "https://github.com/bytecodealliance/wasmtime"
documentation = "https://docs.rs/wasmtime-cache/"
edition.workspace = true

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
file-per-thread-logger = { workspace = true }
pretty_env_logger = { workspace = true }
rayon = "1.5.0"
wasmtime = { workspace = true }

[features]
default = [
    "wasmtime/cache",
    "wasmtime/cranelift",
    "wasmtime/jitdump",
    "wasmtime/vtune",
    "wasmtime/parallel-compilation",
]
pooling-allocator = []
component-model = []
