[package]
name = "cranelift-wasm"
version = "0.111.0"
authors = ["The Cranelift Project Developers"]
description = "Translator from WebAssembly to Cranelift IR"
documentation = "https://docs.rs/cranelift-wasm"
repository = "https://github.com/bytecodealliance/wasmtime"
license = "Apache-2.0 WITH LLVM-exception"
categories = ["no-std", "wasm"]
readme = "README.md"
keywords = ["webassembly", "wasm"]
edition.workspace = true

[lints]
workspace = true

[dependencies]
wasmparser = { workspace = true, features = ['validate'] }
cranelift-codegen = { workspace = true }
cranelift-entity = { workspace = true }
cranelift-frontend = { workspace = true }
wasmtime-types = { workspace = true }
hashbrown = { workspace = true, optional = true }
itertools = "0.12.0"
log = { workspace = true }
serde = { workspace = true, optional = true }
serde_derive = { workspace = true, optional = true }
smallvec = { workspace = true }

[dev-dependencies]
wat = { workspace = true }
target-lexicon = { workspace = true }

[features]
default = ["std"]
std = ["cranelift-codegen/std", "cranelift-frontend/std"]
core = ["hashbrown", "cranelift-codegen/core", "cranelift-frontend/core"]
enable-serde = ["serde", "serde_derive"]
