[package]
name = "cranelift-wasm"
version = "0.75.0"
authors = ["The Cranelift Project Developers"]
description = "Translator from WebAssembly to Cranelift IR"
documentation = "https://docs.rs/cranelift-wasm"
repository = "https://github.com/bytecodealliance/wasmtime"
license = "Apache-2.0 WITH LLVM-exception"
categories = ["no-std", "wasm"]
readme = "README.md"
keywords = ["webassembly", "wasm"]
edition = "2018"

[dependencies]
wasmparser = { version = "0.79", default-features = false }
cranelift-codegen = { path = "../codegen", version = "0.75.0", default-features = false }
cranelift-entity = { path = "../entity", version = "0.75.0" }
cranelift-frontend = { path = "../frontend", version = "0.75.0", default-features = false }
hashbrown = { version = "0.9.1", optional = true }
itertools = "0.10.0"
log = { version = "0.4.6", default-features = false }
serde = { version = "1.0.94", features = ["derive"], optional = true }
smallvec = "1.6.1"
thiserror = "1.0.4"

[dev-dependencies]
wat = "1.0.37"
target-lexicon = "0.12"
# Enable the riscv feature for cranelift-codegen, as some tests require it
cranelift-codegen = { path = "../codegen", version = "0.75.0", default-features = false, features = ["riscv"] }

[features]
default = ["std"]
std = ["cranelift-codegen/std", "cranelift-frontend/std"]
core = ["hashbrown", "cranelift-codegen/core", "cranelift-frontend/core"]
enable-serde = ["serde"]

[badges]
maintenance = { status = "experimental" }
