[package]
name = "peepmatic-souper"
version = "0.68.0"
authors = ["Nick Fitzgerald <fitzgen@gmail.com>"]
edition = "2018"
license = "Apache-2.0 WITH LLVM-exception"
description = "Converting Souper optimizations into Peepmatic DSL"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
souper-ir = { version = "1", features = ["parse"] }
log = "0.4.8"

[dev-dependencies]
peepmatic = { path = "../..", version = "0.68.0" }
peepmatic-test-operator = { version = "0.68.0", path = "../test-operator" }
wast = "28.0.0"
