[package]
name = "wasmtime"
version = "0.9.0"
authors = ["The Wasmtime Project Developers"]
description = "High-level API to expose the Wasmtime runtime"
license = "Apache-2.0 WITH LLVM-exception"
repository = "https://github.com/bytecodealliance/wasmtime"
readme = "README.md"
edition = "2018"

[dependencies]
wasmtime-runtime = { path = "../runtime", version = "0.9.0" }
wasmtime-environ = { path = "../environ", version = "0.9.0" }
wasmtime-jit = { path = "../jit", version = "0.9.0" }
wasmparser = "0.51.1"
target-lexicon = { version = "0.10.0", default-features = false }
anyhow = "1.0.19"
region = "2.0.0"
libc = "0.2"
cfg-if = "0.1.9"
backtrace = "0.3.42"
rustc-demangle = "0.1.16"
lazy_static = "1.4"
wat = { version = "1.0.7", optional = true }

[target.'cfg(target_os = "windows")'.dependencies]
winapi = "0.3.7"

[dev-dependencies]
# for wasmtime.rs
wasi-common = { path = "../wasi-common", version = "0.9.0" }
pretty_env_logger = "0.3.0"
rayon = "1.2.1"
file-per-thread-logger = "0.1.1"
wat = "1.0"

[badges]
maintenance = { status = "actively-developed" }

[features]
default = ['wat']

# Enables experimental support for the lightbeam codegen backend, an alternative
# to cranelift. Requires Nightly Rust currently, and this is not enabled by
# default.
lightbeam = ["wasmtime-jit/lightbeam"]
