[package]
name = "wasmtime"
version = "0.7.0"
authors = ["The Wasmtime Project Developers"]
description = "High-level API to expose the Wasmtime runtime"
license = "Apache-2.0 WITH LLVM-exception"
repository = "https://github.com/bytecodealliance/wasmtime"
readme = "README.md"
edition = "2018"

[lib]
name = "wasmtime"
crate-type = ["lib", "staticlib", "cdylib"]

[dependencies]
wasmtime-runtime = { path = "../runtime" }
wasmtime-environ = { path = "../environ" }
wasmtime-jit = { path = "../jit" }
wasmparser = { version = "0.45.0", default-features = false }
target-lexicon = { version = "0.9.0", default-features = false }
anyhow = "1.0.19"
thiserror = "1.0.4"
region = "2.0.0"

[dev-dependencies]
# for wasmtime.rs
wasi-common = { path = "../wasi-common" }
pretty_env_logger = "0.3.0"
wasmtime-wast = { path = "../wast" }
wasmtime-wasi = { path = "../wasi" }
rayon = "1.2.1"
file-per-thread-logger = "0.1.1"
wat = "1.0"

[badges]
maintenance = { status = "actively-developed" }

[features]
# Enables experimental support for the lightbeam codegen backend, an alternative
# to cranelift. Requires Nightly Rust currently, and this is not enabled by
# default.
lightbeam = ["wasmtime-jit/lightbeam"]
