[package]
name = "wasmtime"
version = "0.12.0"
authors = ["The Wasmtime Project Developers"]
description = "High-level API to expose the Wasmtime runtime"
license = "Apache-2.0 WITH LLVM-exception"
repository = "https://github.com/bytecodealliance/wasmtime"
readme = "README.md"
edition = "2018"

[dependencies]
anyhow = "1.0.19"
backtrace = "0.3.42"
cfg-if = "0.1.9"
lazy_static = "1.4"
libc = "0.2"
region = "2.0.0"
rustc-demangle = "0.1.16"
target-lexicon = { version = "0.10.0", default-features = false }
wasmparser = "0.51.2"
wasmtime-environ = { path = "../environ", version = "0.12.0" }
wasmtime-jit = { path = "../jit", version = "0.12.0" }
wasmtime-profiling = { path = "../profiling", version = "0.12.0" }
wasmtime-runtime = { path = "../runtime", version = "0.12.0" }
wat = { version = "1.0.10", optional = true }
wit-parser = "0.1.1"
wit-schema-version = "0.1"
wit-validator = "0.1"

[target.'cfg(target_os = "windows")'.dependencies]
winapi = "0.3.7"

[dev-dependencies]
file-per-thread-logger = "0.1.1"
pretty_env_logger = "0.3.0"
rayon = "1.2.1"
tempfile = "3.1"
wasi-common = { path = "../wasi-common", version = "0.12.0" }
wat = "1.0.10"
wit-text = "0.5"

[badges]
maintenance = { status = "actively-developed" }

[features]
default = ['wat']

# Enables experimental support for the lightbeam codegen backend, an alternative
# to cranelift. Requires Nightly Rust currently, and this is not enabled by
# default.
lightbeam = ["wasmtime-jit/lightbeam"]

[[test]]
name = "host-segfault"
harness = false
