[package]
name = "wasmtime-types"
version = "0.32.0"
authors = ["The Wasmtime Project Developers"]
description = "WebAssembly type definitions for Cranelift"
license = "Apache-2.0 WITH LLVM-exception"
repository = "https://github.com/bytecodealliance/wasmtime"
documentation = "https://docs.rs/wasmtime-types"
edition = "2018"

[dependencies]
cranelift-entity = { path = "../../cranelift/entity", version = "0.79.0", features = ['enable-serde'] }
serde = { version = "1.0.94", features = ["derive"] }
thiserror = "1.0.4"
wasmparser = { version = "0.81", default-features = false }
