[package]
name = "test-programs"
version = "0.0.0"
authors = ["The Wasmtime Project Developers"]
readme = "README.md"
edition.workspace = true
publish = false
license = "Apache-2.0 WITH LLVM-exception"

[build-dependencies]
cfg-if = { workspace = true }
cargo_metadata = "0.15.3"
wit-component = { workspace = true }
heck = { workspace = true }

[dependencies]
anyhow = { workspace = true }
http = { version = "0.2.9" }
http-body = "1.0.0-rc.2"
http-body-util = "0.1.0-rc.2"
hyper = { version = "1.0.0-rc.3", features = ["full"] }
is-terminal = { workspace = true }
tokio = { workspace = true, features = ["net", "rt-multi-thread", "macros"] }
tracing = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
tempfile = { workspace = true }
test-log = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
lazy_static = "1"
wasmtime = { workspace = true, features = ['cranelift', 'component-model'] }

wasi-common = { workspace = true }
wasi-cap-std-sync = { workspace = true }
wasmtime-wasi = { workspace = true, default-features = true, features = [
    "tokio",
] }
cap-std = { workspace = true }
cap-rand = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }

wasmtime-wasi-http = { workspace = true, features = ["sync"] }

[features]
test_programs = []
