[package]
name = "test-programs"
version = "0.19.0"
authors = ["The Wasmtime Project Developers"]
readme = "README.md"
edition = "2021"
publish = false
license = "Apache-2.0 WITH LLVM-exception"

[build-dependencies]
cfg-if = "1.0"

[dev-dependencies]
wasi-common = { path = "../wasi-common", version = "0.39.0" }
wasi-cap-std-sync = { path = "../wasi-common/cap-std-sync", version = "0.39.0" }
wasmtime = { path = "../wasmtime", version = "0.39.0" }
wasmtime-wasi = { path = "../wasi", version = "0.39.0", features = ["tokio"] }
target-lexicon = "0.12.0"
pretty_env_logger = "0.4.0"
tempfile = "3.1.0"
os_pipe = "0.9"
anyhow = "1.0.19"
wat = "1.0.42"
cap-std = "0.24.1"
tokio = { version = "1.8.0", features = ["rt-multi-thread"] }

[features]
test_programs = []
