[package]
name = "test-programs"
version = "0.0.0"
authors = ["The Wasmtime Project Developers"]
readme = "README.md"
edition.workspace = true
publish = false
license = "Apache-2.0 WITH LLVM-exception"

[build-dependencies]
cfg-if = "1.0"
cargo_metadata = "0.15.3"

[dev-dependencies]
wasi-common = { workspace = true }
wasi-cap-std-sync = { workspace = true }
wasmtime = { workspace = true, features = ['cranelift'] }
wasmtime-wasi = { workspace = true, features = ["tokio"] }
target-lexicon = { workspace = true }
tracing-subscriber = { version = "0.3.1", default-features = false, features = ['fmt'] }
tempfile = "3.1.0"
os_pipe = "0.9"
anyhow = { workspace = true }
wat = { workspace = true }
cap-std = { workspace = true }
tokio = { version = "1.8.0", features = ["rt-multi-thread"] }
wasi-http = { workspace = true }

[features]
test_programs = []
test_programs_http = [ "wasmtime/component-model" ]
