[package]
name = "test-programs"
version = "0.7.0"
authors = ["The Wasmtime Project Developers"]
readme = "README.md"
edition = "2018"
publish = false

[build-dependencies]
cfg-if = "0.1.9"

[dev-dependencies]
wasi-common = { path = "../wasi-common" }
wasmtime-runtime = { path = "../runtime" }
wasmtime-environ = { path = "../environ" }
wasmtime-jit = { path = "../jit" }
wasmtime-wasi = { path = "../wasi" }
wasmtime = { path = "../api" }
cranelift-codegen = "0.50.0"
target-lexicon = "0.9.0"
pretty_env_logger = "0.3.0"
tempfile = "3.1.0"
os_pipe = "0.9"
anyhow = "1.0.19"
wat = "1.0.2"

[features]
test_programs = []
