[package]
name = "test-programs"
version = "0.19.0"
authors = ["The Wasmtime Project Developers"]
readme = "README.md"
edition = "2018"
publish = false
license = "Apache-2.0 WITH LLVM-exception"

[build-dependencies]
cfg-if = "1.0"

[dev-dependencies]
wasi-c2 = { path = "../wasi-c2", version = "0.22.0" }
wasi-c2-wasmtime = { path = "../wasi-c2/wasmtime", version = "0.22.0" }
wasmtime = { path = "../wasmtime", version = "0.22.0" }
target-lexicon = "0.11.0"
pretty_env_logger = "0.4.0"
tempfile = "3.1.0"
os_pipe = "0.9"
anyhow = "1.0.19"
wat = "1.0.23"
cap-std = "0.8"

[features]
test_programs = []
