[package]
name = "test-programs"
version = "0.19.0"
authors = ["The Wasmtime Project Developers"]
readme = "README.md"
edition = "2018"
publish = false

[build-dependencies]
cfg-if = "1.0"

[dev-dependencies]
wasi-common = { path = "../wasi-common", version = "0.20.0" }
wasmtime-wasi = { path = "../wasi", version = "0.20.0" }
wasmtime = { path = "../wasmtime", version = "0.20.0" }
target-lexicon = "0.11.0"
pretty_env_logger = "0.4.0"
tempfile = "3.1.0"
os_pipe = "0.9"
anyhow = "1.0.19"
wat = "1.0.23"

[features]
test_programs = []
