[package]
name = "test-programs-artifacts"
version = "0.0.0"
authors = ["The Wasmtime Project Developers"]
edition.workspace = true
publish = false
license = "Apache-2.0 WITH LLVM-exception"

[lints]
workspace = true

[dependencies]
wasmtime = { workspace = true, features = ['incremental-cache', 'cranelift', 'component-model'] }

[build-dependencies]
heck = { workspace = true }
wasi-preview1-component-adapter-provider = { workspace = true }
wit-component = { workspace = true }
cargo_metadata = "0.18.1"
