[package]
name = "cranelift-native"
version = "0.72.0"
authors = ["The Cranelift Project Developers"]
description = "Support for targeting the host with Cranelift"
documentation = "https://docs.rs/cranelift-native"
repository = "https://github.com/bytecodealliance/wasmtime"
categories = ["no-std"]
license = "Apache-2.0 WITH LLVM-exception"
readme = "README.md"
edition = "2018"

[dependencies]
cranelift-codegen = { path = "../codegen", version = "0.72.0", default-features = false }
target-lexicon = "0.11"

[features]
default = ["std"]
std = ["cranelift-codegen/std"]
core = ["cranelift-codegen/core"]

[badges]
maintenance = { status = "experimental" }
