[package]
name = "wasmtime-py"
version = "0.2.0"
authors = ["The Wasmtime Project Developers"]
description = "Python extension for Wasmtime"
license = "Apache-2.0 WITH LLVM-exception"
categories = ["wasm", "python"]
edition = "2018"

[lib]
name = "_wasmtime"
crate-type = ["cdylib"]

[dependencies]
cranelift-codegen = { version = "0.49" }
cranelift-native = { version = "0.49" }
cranelift-entity = { version = "0.49" }
cranelift-wasm = { version = "0.49" }
cranelift-frontend = { version = "0.49" }
wasmtime-environ = { path = "../../environ" }
wasmtime-interface-types = { path = "../../interface-types" }
wasmtime-jit = { path = "../../jit" }
wasmtime-runtime = { path = "../../runtime" }
target-lexicon = { version = "0.9.0", default-features = false }
anyhow = "1.0.19"
region = "2.0.0"
wasmparser = "0.39.2"

[dependencies.pyo3]
version = "0.8.0"
features = ["extension-module"]
