[package]
name = "wiggle-macro"
version = "0.24.0"
authors = ["Pat Hickey <phickey@fastly.com>", "Jakub Konka <kubkon@jakubkonka.com>", "Alex Crichton <alex@alexcrichton.com>"]
edition = "2018"
license = "Apache-2.0 WITH LLVM-exception"
description = "Wiggle code generator"
categories = ["wasm"]
keywords = ["webassembly", "wasm"]
repository = "https://github.com/bytecodealliance/wasmtime"
include = ["src/**/*", "LICENSE"]

[lib]
proc-macro = true
test = false

# This has been added to make testing of the experimental_x64 feature possible,
# working around a Cargo nightly bug: once
# https://github.com/rust-lang/cargo/issues/8563 has been fixed, we should be
# able to revert it.
doctest = false

[dependencies]
wiggle-generate = { path = "../generate", version = "0.24.0" }
witx = { version = "0.9", path = "../../wasi-common/WASI/tools/witx" }
quote = "1.0"
syn = { version = "1.0", features = ["full"] }

[dev-dependencies]
wiggle = { path = ".." }

[features]
wiggle_metadata = []
