[package]
authors = ["The Winch Project Developers"]
name = "winch-environ"
description = "Implementation of Winch's function compilation environment"
license = "Apache-2.0 WITH LLVM-exception"
repository = "https://github.com/bytecodealliance/wasmtime"
version = "0.6.0"
edition.workspace = true


[dependencies]
winch-codegen = { workspace = true }
wasmtime-environ = { workspace = true }
wasmparser = { workspace = true }
