[package]
name = "lightbeam"
version = "0.27.0"
authors = ["The Lightbeam Project Developers"]
description = "An optimising one-pass streaming compiler for WebAssembly"
license = "Apache-2.0 WITH LLVM-exception"
repository = "https://github.com/bytecodealliance/wasmtime"
readme = "README.md"
categories = ["wasm"]
keywords = ["webassembly", "wasm", "compile", "compiler", "jit"]
edition = "2018"

[dependencies]
arrayvec = "0.5"
capstone = "0.8.0"
cranelift-codegen = { path = "../../cranelift/codegen", version = "0.74.0" }
derive_more = "0.99"
dynasm = "1.0.0"
dynasmrt = "1.0.0"
iter-enum = "1"
itertools = "0.10.0"
memoffset = "0.6.0"
more-asserts = "0.2.1"
smallvec = "1.6.1"
thiserror = "1.0.9"
typemap = "0.3"
wasmparser = "0.78"

[dev-dependencies]
lazy_static = "1.2"
wat = "1.0.37"
quickcheck = "1.0.0"
anyhow = "1.0"

[badges]
maintenance = { status = "experimental" }
