[package]
name = "wig"
version = "0.19.0"
authors = ["Dan Gohman <sunfish@mozilla.com>"]
description = "WebAssembly Interface Generator"
license = "Apache-2.0 WITH LLVM-exception"
categories = ["wasm"]
keywords = ["webassembly", "wasm"]
repository = "https://github.com/bytecodealliance/wasmtime"
edition = "2018"
include = ["src/**/*", "LICENSE", "WASI"]

[lib]
proc-macro = true
test = false

[dependencies]
quote = "1.0.2"
proc-macro2 = "1.0.6"
heck = "0.3.1"
witx = { path = "../WASI/tools/witx", version = "0.8.5" }

[badges]
maintenance = { status = "actively-developed" }
