[package]
name = "cranelift-codegen-meta"
authors = ["The Cranelift Project Developers"]
version = "0.117.0"
description = "Metaprogram for cranelift-codegen code generator library"
license = "Apache-2.0 WITH LLVM-exception"
repository = "https://github.com/bytecodealliance/wasmtime"
readme = "README.md"
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[package.metadata.docs.rs]
rustdoc-args = ["--document-private-items"]

[dependencies]
cranelift-assembler-x64 = { path = "../../assembler-x64", version = "0.117.0" }
cranelift-codegen-shared = { path = "../shared", version = "0.117.0" }
pulley-interpreter = { workspace = true, optional = true }

[features]
pulley = ['dep:pulley-interpreter']
