[package]
name = "cranelift-codegen-meta"
authors = ["The Cranelift Project Developers"]
version = "0.71.0"
description = "Metaprogram for cranelift-codegen code generator library"
license = "Apache-2.0 WITH LLVM-exception"
repository = "https://github.com/bytecodealliance/wasmtime"
readme = "README.md"
edition = "2018"

[package.metadata.docs.rs]
rustdoc-args = [ "--document-private-items" ]

[dependencies]
cranelift-codegen-shared = { path = "../shared", version = "0.71.0" }
cranelift-entity = { path = "../../entity", version = "0.71.0" }

[badges]
maintenance = { status = "experimental" }
