[package]
name = "wasmtime-rust"
version = "0.2.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
edition = "2018"
categories = ["wasm", "rust"]
license = "Apache-2.0 WITH LLVM-exception"
description = "Rust extension for Wasmtime"

[lib]
test = false
doctest = false

[dependencies]
cranelift-codegen = "0.44.0"
cranelift-native = "0.44.0"
failure = "0.1.5"
wasmtime-interface-types = { path = "../../wasmtime-interface-types" }
wasmtime-jit = { path = "../../wasmtime-jit" }
wasmtime-rust-macro = { path = "./macro" }
