[package]
name = "clif-wasm-fuzz"
version = "0.0.1"
authors = ["foote@fastly.com"]
publish = false
edition = "2018"

[package.metadata]
cargo-fuzz = true

[dependencies]
cargo-fuzz = "*"
binaryen = { git = "https://github.com/pepyakin/binaryen-rs.git" }
libfuzzer-sys = { git = "https://github.com/rust-fuzz/libfuzzer-sys.git" }
cranelift-codegen = { path = "../codegen" }
cranelift-wasm = { path = "../wasm" }
cranelift-reader = { path = "../reader" }
target-lexicon = "0.10"

# Prevent this from interfering with workspaces
[workspace]
members = ["."]

[[bin]]
name = "fuzz_translate_module"
path = "fuzz_translate_module.rs"

[[bin]]
name = "fuzz_reader_parse_test"
path = "fuzz_reader_parse_test.rs"
