[package]
authors = ["The Cranelift Project Developers"]
name = "cranelift"
version = "0.75.0"
description = "Umbrella for commonly-used cranelift crates"
license = "Apache-2.0 WITH LLVM-exception"
documentation = "https://docs.rs/cranelift"
repository = "https://github.com/bytecodealliance/wasmtime"
categories = ["no-std"]
readme = "README.md"
keywords = ["compile", "compiler", "jit"]
edition = "2018"

[dependencies]
cranelift-codegen = { path = "../codegen", version = "0.75.0", default-features = false }
cranelift-frontend = { path = "../frontend", version = "0.75.0", default-features = false }

[features]
default = ["std"]
std = ["cranelift-codegen/std", "cranelift-frontend/std"]
core = ["cranelift-codegen/core", "cranelift-frontend/core"]

[badges]
maintenance = { status = "experimental" }
