[package]
authors = ["The Cranelift Project Developers"]
name = "cranelift"
version = "0.107.2"
description = "Umbrella for commonly-used cranelift crates"
license = "Apache-2.0 WITH LLVM-exception"
documentation = "https://docs.rs/cranelift"
repository = "https://github.com/bytecodealliance/wasmtime"
categories = ["no-std"]
readme = "README.md"
keywords = ["compile", "compiler", "jit"]
edition.workspace = true

[dependencies]
cranelift-codegen = { workspace = true }
cranelift-frontend = { workspace = true }

[features]
default = ["std"]
std = ["cranelift-codegen/std", "cranelift-frontend/std"]
core = ["cranelift-codegen/core", "cranelift-frontend/core"]
