[package]
name = "wasmtime-bench-api"
version.workspace = true
authors.workspace = true
description = "Exposes a benchmarking API for the Wasmtime runtime"
license = "Apache-2.0 WITH LLVM-exception"
repository = "https://github.com/bytecodealliance/wasmtime"
readme = "README.md"
edition.workspace = true
rust-version.workspace = true
publish = false

[lints]
workspace = true

[lib]
name = "wasmtime_bench_api"
crate-type = ["cdylib"]
doctest = false

[dependencies]
anyhow = { workspace = true }
shuffling-allocator = { version = "1.1.1", optional = true }
target-lexicon = { workspace = true }
wasmtime = { workspace = true, default-features = true, features = ["winch", 'pulley'] }
wasmtime-cli-flags = { workspace = true, default-features = true, features = [
    "cranelift",
] }
wasi-common = { workspace = true, default-features = true }
wasmtime-wasi-nn = { workspace = true, optional = true }
cap-std = { workspace = true }
clap = { workspace = true }

[dev-dependencies]
wat = { workspace = true }

[features]
default = ["shuffling-allocator", "wasi-nn"]
wasi-nn = ["wasmtime-wasi-nn"]
